name: "Edit configuration files"
description: "Edit yaml, toml or json files"
branding:
  icon: "edit"
  color: "blue"

inputs:
  file:
    description: "File input path"
    required: true

  key:
    description: "Key to change"
    required: true

  value:
    description: "Value to input"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruamel.yaml==0.17.21 toml==0.10.2
      shell: bash
    - run: python ${{ github.action_path }}/main.py ${{ inputs.file }} ${{ inputs.key }} ${{ inputs.value }}
      shell: bash
      id: run
