name: Edit yaml

on:
  workflow_dispatch:

jobs:
  edit-yaml:
    name: Edit Yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update version in deployment.yaml with release tag
        uses: Hojland/gha-configedit@v0.0.4
        with:
          file: "test.json"
          key: "key1.key2"
          value: "value2"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: update test.yaml with value2 value"
          branch: main
